### PR TITLE
Release/1.2.1

### PR DESCRIPTION
**Pull request by MedAziz11**

### CODE REVIEW

**Comment by nstankov-bg** [comment]
Testing something new for cross-arch builds, as the matrix is not exactly playing well with dockerhub. It's a veery special registry, unfortunately.

**Review by MedAziz11 — COMMENTED** [review]
thnks to @nstankov-bg for his amazing work and contributions ! 🎉🎉

**Comment by MedAziz11** [comment]
ill try it in this oull request if it is working or no in the main branch

**Comment by nstankov-bg** [comment]
PR coming for another release candidate in the next 10m. Thanks for everything.

**Comment by MedAziz11** [comment]
whats exactly in the PR?

**Comment by nstankov-bg** [comment]
> whats exactly in the PR?

Just pushed it. Replacing the matrix, so we play natively with dockerhub multi-arch, vs multi-tag.

**Comment by nstankov-bg** [comment]
Screenshot 2023-04-16 at 9 25 04 AM

**Comment by MedAziz11** [comment]
tbh thats a good one lol never knew there is a feature like this in docker hub

**Comment by MedAziz11** [comment]
@nstankov-bg lol i think the tag workflow only works when the tag starts with "v" and not "V",  imma investigate

**Comment by MedAziz11** [comment]
yup as i said

**Pull request merged**
