### PR TITLE
feature/improve-CI

### PR DESCRIPTION
**Pull request by nstankov-bg**
### Summary

Hello fellow developers! 👋 I've updated the GitHub Actions YAML file to include some useful new features and optimizations. Here's a quick rundown of the changes:

### Tested

[Private test link, with all variables added to my fork](https://github.com/nstankov-bg/Uptime-Kuma-Web-API/actions/runs/4684354096)
### Issues

This will help build & test cross-platform images to address items like: #2 

### Description

1. **Added support for multiple branches:** Now, the workflow will run on both `main` and `develop` branches, as well as any tagged commits following the pattern `v*.*.*`.
2. **Environment variables for DockerHub repo and image:** Introduced environment variables to make it easier to maintain and change the DockerHub repository and image names in the future. You'll need to set the `DOCKERHUB_REPO` and `DOCKERHUB_IMAGE` variables in your GitHub repository's settings.
3. **Docker Buildx setup:** I've incorporated the Docker Buildx setup to take advantage of advanced features like caching and multi-platform builds.
4. **Caching Docker layers:** To speed up build times, I've added caching for Docker layers using the `actions/cache@v2` action.
5. **Dynamic image tagging:** The image tags are now dynamically set based on the branch or tag being built. The `main` branch will be tagged as `latest`, the `develop` branch as `dev`, and any tagged commits will have the corresponding version tag (e.g., `v1.2.3`).

---

### Required GitHub Secrets

Please make sure you have the following GitHub Secrets set up in your repository's settings:

- `DOCKER_USERNAME`: Your Docker Hub username.
- `DOCKER_PASSWORD`: Your Docker Hub access token.

These changes should make our Docker CI workflow more efficient and easier to manage. Enjoy the upgrade! 🎉

### Required GitHub Variables

Please make sure you have the following GitHub Variables setup in your repository's settings:

- `DOCKERHUB_REPO`: Your Docker Hub username(this can just be a namespace too)
- `DOCKERHUB_IMAGE`: Your Docker Hub image name

### CODE REVIEW

**Comment by MedAziz11** [comment]
wow rlly wow thnx aloooot for the contribution and amazing work

**Review by MedAziz11 — COMMENTED** [review]
amazing ideas 🚀🚀 btw do u have twitter or smthing?

**Comment by MedAziz11** [comment]
so i merged it into the develop branch to trigger the workflow , i kinda ran into an issue `"ERROR: push and load may not be set together at the moment"` so i deleted the `load: true` from the  `main.yml ` and it worked but i think there is a problem or is it meant to be like that .
i dont see the need of pushing into the main branch while i just updated my develop branch and the dynamic image tagging isnt working as expected 
image

**Comment by nstankov-bg** [comment]
> amazing ideas 🚀🚀 btw do u have twitter or smthing?

I am one of those incognito people w/o social media, as a fan of privacy.
I will gladly connect with you if you open a discussions board in the repository, to keep a reasonable degree of communication.

**Pull request merged**
