### PR TITLE
[READY FOR REVIEW] 🚀 [BUG]: Update Docker GitHub Action(s)

### PR DESCRIPTION
**Pull request by nstankov-bg**
# Bug introduced

* Fixes bug in: #24 

# Description

This PR updates the Docker GitHub Action configuration to resolve the conflict between `load` and `test`, and it now generates the following combinations of tags for each branch and platform:

- 🏗️ `main` branch and `linux/amd64` platform:
  - `main`
  - `main-linux-amd64`
- 🏗️ `main` branch and `linux/arm64` platform:
  - `main`
  - `main-linux-arm64`
- 🌱 `develop` branch and `linux/amd64` platform:
  - `develop`
  - `develop-linux-amd64`
- 🌱 `develop` branch and `linux/arm64` platform:
  - `develop`
  - `develop-linux-arm64`

The matrix strategy creates a build for each branch and platform combination. In total, it creates 4 jobs, as there are 2 branches and 2 platforms. 🏁

### CODE REVIEW

**Comment by MedAziz11** [comment]
do we really feel the need to push images with tag "main" if we push to the main branch  ?
nope i dont think so , the idea is to push images depending on the release version  or dev (dev just for us to run tests or something and make sure everything is running before merging to main). ill try to figure out a way to do that cuz its my first time using github action

**Comment by nstankov-bg** [comment]
That's a fair comment, instead of main, it can just go to :latest, which is the general thing that images do?

**Comment by nstankov-bg** [comment]
> My vision right now :
> 
>     * Push on develop: build + push image , tag= dev
> 
>     * Push main or new tag : build + push image , tag = version and latest
> 
> 
> More improvements on the future:
> 
>     * push on develop: build + run tests + if test succeeded then push
> 
>     * Push main or new tag : build+ run tests + if test succeeded then push  push image else open issue
> 
>     * pull request on develop : run old test to make sure there is no regression
> 
> 
> (For now we can avoid using the buildx if it is making problems)

Updated per your request.
I tried to keep buildx, as I do have a general need on this being cross-architecture.

**Comment by nstankov-bg** [comment]
You still around my friend @MedAziz11?

**Comment by MedAziz11** [comment]
yes yes , just had alot of things to do with work and stuff the last few days

**Review by MedAziz11 — APPROVED** [review]

**Pull request merged**
